# Generated by Django 4.2.9 on 2024-04-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_platform_enable_customuser_alter_platform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
