# Generated by Django 4.2.9 on 2024-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phto',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
