# Generated by Django 4.2.9 on 2024-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_phto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phto',
            new_name='photo',
        ),
    ]
