# Generated by Django 4.2.9 on 2024-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_enable_platform_enabled_useradditionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='user_photo',
            field=models.ImageField(default='static/avatars/dummy.png', upload_to='static/avatars/'),
        ),
    ]
