# Generated by Django 4.2.9 on 2024-04-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_useradditionalinfo_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditionalinfo',
            old_name='user_photo',
            new_name='profile_picture',
        ),
    ]
