# Generated by Django 4.2.9 on 2024-04-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_user_photo_useradditionalinfo_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditionalinfo',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
