# Generated by Django 4.2.9 on 2024-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_profile_picture_useradditionalinfo_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='profilePicture',
            field=models.ImageField(default='static/avatars/dummy.png', upload_to='profile_picture/'),
        ),
    ]
