# Generated by Django 4.2.9 on 2024-04-28 05:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_useradditionalinfo_profilepicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform',
            new_name='PlatformCategory',
        ),
    ]
