# Generated by Django 4.2.9 on 2024-05-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_debugcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=100)),
                ('value_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_currency', models.CharField(choices=[('THB', 'THB - Thai Baht'), ('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JYP', 'JYP - Japanese Yen'), ('PHP', 'PHP - Philippine Peso')], max_length=3)),
                ('note', models.CharField(max_length=500)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('raw_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_currency', models.CharField(choices=[('THB', 'THB - Thai Baht'), ('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('JYP', 'JYP - Japanese Yen'), ('PHP', 'PHP - Philippine Peso')], max_length=3)),
                ('note', models.CharField(max_length=300)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
