# Generated by Django 4.2.9 on 2024-05-22 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_savingdata_incomeexpensedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingData',
            new_name='AssetData',
        ),
        migrations.RenameField(
            model_name='incomeexpensedata',
            old_name='last_edit',
            new_name='lastEdit',
        ),
        migrations.RenameField(
            model_name='incomeexpensedata',
            old_name='last_edit_by',
            new_name='lastEditBy',
        ),
        migrations.RenameField(
            model_name='incomeexpensedata',
            old_name='raw_amount',
            new_name='rawAmount',
        ),
        migrations.RenameField(
            model_name='incomeexpensedata',
            old_name='raw_currency',
            new_name='rawCurrency',
        ),
        migrations.RenameField(
            model_name='incomeexpensedata',
            old_name='transaction_date_time',
            new_name='transactionDateTime',
        ),
    ]
