# Generated by Django 4.2.9 on 2024-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_incomeexpensedata_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpensedata',
            name='platform',
            field=models.CharField(max_length=100),
        ),
    ]
